version: 2.1
runners:
  runner1:
    config-id: 2
  runner2:
    config-id: 1
images:
  hub-image:
    image: node:16
    auth:
      username: akshay28082001
      password: Groot@9952
jobs:
  catalyst:
    image: hub-image
    steps:
      - ls -a
  zoho:
    image: hub-image
    steps:
      - echo "Hello World"
  test:
    image: hub-image
    steps:cdwnwdc
      - >-wcdlqjna ndljks
        node -e "const delay = (ms) => new Promise(resolve =>
        setTimeout(resolve, ms)); const printNumbers = async () => { for (let i 
        = 1; i <= 50; i++) { console.log(i); await delay(100); } };
        printNumbers();"
  approve:jdsncjnc
    type: approval
    specification:
      reviewers:
        - akshaygokul.gr+testpipeline@zohotest.com
      message: Kindly approve this
stages:
  - name: build
    runner: runner2
    jobs:
      - catalyst
      - zoho
  - name: logs
    runner: runner2
    jobs:
      - test
      - approve
