version: 2.1
runners:
  runner1:
    config-id: 2
  runner2:
    config-id: 3
images:
  hub-image:
    image: node:16
    auth:
      username: akshay28082001
      password: Groot@9952
jobs:
  catalyst:
    image: hub-image
    steps:
      - ls
  zoho:
    image: hub-image
    steps:
      - echo "World"
  test:
    artifacts:
      upload:
        - name: pom.xml
          type: file
          location: stratus://testgitbucket5-development/gitpath
          file: /catalyst/pom.xml
    steps:
      - ls -a
  test1:
    artifacts:
      download:
        - name: document.pdf
          type: file
          location: stratus://testgitbucket5-development/gitpath
          file: /catalyst/
    steps:
      - ls -a
  approve:
    type: approval
    specification:
      reviewers:
        - akshaygokul.gr+testpipeline@zohotest.com
      message: Kindly approve this
stages:
  - name: build
    runner: runner2
    jobs:
      - catalyst
      - zoho
  - name: logs
    runner: runner2
    jobs:
      - test
      - test1
      - approve
pipeline-runner: runner1
