version: 2.1
runners:
  runner1:
    config-id: 2
  runner2:
    config-id: 3 
images: 
  hub-image:
    image: ollama/ollama
    auth:
      username: akshay28082001
      password: Groot@9952
jobs:
  catalyst:
    steps:
      - ls -a
  zoho: 
    image: hub-image 
    steps:
      - ls
      - echo "World!"
  test:
    steps:
      - ls -a
  approve:
    type: approval
    specification:
      reviewers:
        -  akshaygokul.gr+testpipeline@zohotest.com
      message: Kindly approve this
  test1:
    steps:
      - ls -a
stages:
  - name: build
    runner: runner2
    jobs:
      - catalyst
      - test
      - zoho
  - name: logs
    runner: runner2
    jobs:
      - approve
pipeline-runner: runner1