version: 1
stages:
  - name: mystage
    jobs:
      - test1
jobs:
  test1:
    artifacts:
      upload:
        - type: zip
          name: test.zip
          location: stratus://pipelinerelease/gitpath
          regex: 
            - /catalyst/src/**/
    steps:
      - free -h