version: 2.1
runners: 
  runner1:
    config-id: 2
  runner2:
    config-id: 3 
images:  
  hub-image: 
    image: ollama/ollama
    auth:
      username: akshay28082001
      password: Groot@9952
jobs:
  catalyst:
    steps:
      - ls -a
  zoho: 
    image: hub-image
    steps:
      - ls
      - echo "World!"
  test:
    artifacts:
      upload:
        - name: pom.xml
          type: file
          location: stratus://cvbnmz/gitpath
          file: pom.xml
    steps:
      - ls -a
  approve:
    type: approval
    specification:
      reviewers:
        -  akshaygokul.gr+pipelinerelease@zohotest.com
      message: Kindly approve this
  test1:
    artifacts:
      download:
        - name: document.pdf
          type: file
          location: stratus://cvbnmz/gitpath
          file: /docs/document.pdf
    steps:
      - cd docs  
      - ls -a

  test2:
    artifacts:
      upload:
        - type: zip
          name: test.zip
          location: stratus://cvbnmz/
          regex: 
            - /catalyst/src/**/
    steps:
      - pwd

stages:
  - name: build
    runner: runner2
    jobs:
      - catalyst
    #   - test
    #   - test1
    #   - test2
      - zoho
  - name: logs
    runner: runner2
    jobs:
      - approve
pipeline-runner: runner1