version: 1
stages:
  - name: mystage
    jobs:
      - test1
jobs:
  test1:
    artifacts:
      upload:
        - type: zip
          name: test.zip
          location: stratus://pipelinerelease/gitpath
          regex:
            - /catalyst/src/**/
    steps:
      - free -h
      - lscpu
      - cat /proc/cpuinfo
      - lsblk
      - df -h
runners:
  testrunner:
    config-id: 3
pipeline-runner: testrunner