version: 1
stages:
  - name: mystage
    jobs:
      - test1
      - test2
jobs:
  test1:
    artifacts:
      upload:
        - type: zip
          name: test.zip
          location: stratus://pipelinerelease/gitpath
          regex:
            - /catalyst/src/**/
    steps:
      - cat src/test/java/com/houarizegai/calculator/CalculatorUITest.java

  test2:
    artifacts:
      download:
        - name: test.zip
          type: file
          location: stratus://pipelinerelease/gitpath
          file: /newtest/
    steps:
        - cd newtest
        - pwd
        - ls -a
runners:
  testrunner:
    config-id: 1
pipeline-runner: testrunner