version: 1
stages:
  - name: mystage
    jobs:
      - test1
jobs:
  test1:
    artifacts:
      upload:
        - type: zip
          name: test.zip
          location: stratus://pipelinerelease/gitpath
          regex:
            - /catalyst/src/**/
    steps:
      - cat src/test/java/com/houarizegai/calculator/CalculatorUITest.java
runners:
  testrunner:
    config-id: 1
pipeline-runner: testrunner