version: 2.1
runners:
  runner1:
    config-id: 2
  runner2:
    config-id: 3
images:
  hub-image:
    image: ollama/ollama
    auth:
      username: akshay28082001
      password: Groot@9952

    steps:
      - ls -a
  test1:
    artifacts:
      download:
        - name: document.pdf
          type: file
          location: stratus://testgitbucket3-development/gitpath
          file: /catalyst/
    steps:
      - ls -a
stages:
  - name: build
    runner: runner2
    jobs:
      - catalyst
      - test
      - test1
pipeline-runner: runner1
