version: 2.1
runners:
  runner1:
    config-id: 2
  runner2:
    config-id: 3
images:
  hub-image:
    image: node:16
    auth:
      username: akshay28082001
      password: Groot@9952
jobs:
  catalyst:
    steps:
      - >-
        curl -o abc.hdr
        https://filesamples.com/samples/image/hdr/sample_640%C3%97426.hdr
      - pwd
      - ls -a
  zoho:
    image: hub-image
    steps:
      - echo "World"
  test:
    artifacts:
      upload:
        - name: pom.xml
          type: file
          location: stratus://gitbucket/gitpath
          file: /catalyst/pom.xml
    steps:
      - >-
        node -e "const delay = (ms) => new Promise(resolve =>
        setTimeout(resolve, ms)); const printNumbers = async () => { for (let i
        = 1; i <= 50; i++) { console.log(i); await delay(100); } };
        printNumbers();"
  approve:
    type: approval
    specification:
      reviewers:
        - akshaygokul.gr+pricing@zohotest.com
      message: Kindly approve this
  test1:
    artifacts:
      download:
        - name: pom.xml
          location: stratus://gitbucket/gitpath
          file: /catalyst/src/
    steps:
      - cd
stages:
  - name: build
    runner: runner2
    jobs:
      - catalyst
      - test1
      - zoho
  - name: logs
    runner: runner2
    jobs:
      - approve
pipeline-runner: runner1