version: 1
stages:
  - name: mystage
    jobs:
      - test1
jobs:
  test1:
    artifacts:
      upload:
        - type: zip
          name: test.zip
          location: stratus://pipelinerelease/gitpath
          regex:
            - /catalyst/src/**/
    steps:
      - cat /proc/sys/kernel/random/entropy_avail
      - apt-get install rng-tools
      - ls -l /dev/hwrng
runners:
  testrunner:
    config-id: 1
pipeline-runner: testrunner